<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>PyVSwitch</RootNamespace>
    <AssemblyName>PyVSwitch.Core</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="PyVSwitch.Tests" />
  </ItemGroup>

</Project>
